New branch with Week 4 commits
evd123/step pull request #3
Opened 2020-06-09 14:21 UTC by evd123

I reverted Pull Request #2 (WebApp Updates) to before making the Maps API changes and moved those changes to this branch and pull request.

2020-06-09 18:56 UTC, lcatherine requested changes
There are some spacing / newline issues throughout. 

Also you can remove the ToDo for handling comments since it has been handled :D

2020-06-11 13:25 UTC, lcatherine commented
It looks like there are conflicts, please resolve before merging

2020-06-16 14:22 UTC, lyze requested changes

2020-06-16 14:22 UTC, lyze commented on portfolio/src/main/java/com/google/sps/servlets/TravelDataServlet.java
> +    response.getWriter().println(gson.toJson(voteCount));
gson.ToJson(voteCount, gson.newJsonWriter(response.getWriter());

2020-06-16 14:22 UTC, lyze commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    response.getWriter().println(gson.toJson(allMessages));
gson.toJson(allMessages, gson.newJsonWriter(response.getWriter()));

2020-06-16 14:42 UTC, lcatherine commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    List < Message > allMessages = new ArrayList < > ();
weird spacing around the angled brackets

2020-06-16 14:43 UTC, lcatherine commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +  Function to check if email is submitted if the user wants a response. Don't think this function actually does anything.
"Don't think this function actually does anything." 🤔  So should this be removed or fixed?

2020-06-16 15:06 UTC, lcatherine commented on portfolio/src/main/java/com/google/sps/servlets/TravelDataServlet.java
> +import java.util.Map;
unused

2020-06-16 15:06 UTC, lcatherine commented on portfolio/src/main/java/com/google/sps/servlets/TravelDataServlet.java
> +import java.util.Scanner;
same

2020-06-16 15:08 UTC, merged